name=input("enter the name of the student: ")
print(name)
print(type(name))
sid=int(input("enter the student roll number: "))
print(sid)
print( type(sid))
maths=eval(input("enter the maths marks:"))
print(maths)
print(type(maths))
